// Major international airports — IATA + ICAO + name + city + lat/lon.
// Curated list of ~90 of the busiest hubs worldwide. Used as a Cesium
// label layer and as click-to-fly-to bookmarks in Cmd+K.

export type Airport = {
  iata: string;
  icao: string;
  name: string;
  city: string;
  country: string;          // ISO 3166-1 alpha-2
  lat: number;
  lon: number;
};

export const AIRPORTS: Airport[] = [
  // Top 50 busiest by passenger traffic (rough order)
  { iata: "ATL", icao: "KATL", name: "Hartsfield-Jackson",     city: "Atlanta",       country: "US", lat:  33.6407, lon:  -84.4277 },
  { iata: "DXB", icao: "OMDB", name: "Dubai International",    city: "Dubai",         country: "AE", lat:  25.2532, lon:   55.3657 },
  { iata: "DFW", icao: "KDFW", name: "Dallas/Fort Worth",      city: "Dallas",        country: "US", lat:  32.8998, lon:  -97.0403 },
  { iata: "HND", icao: "RJTT", name: "Tokyo Haneda",           city: "Tokyo",         country: "JP", lat:  35.5494, lon:  139.7798 },
  { iata: "LHR", icao: "EGLL", name: "London Heathrow",        city: "London",        country: "GB", lat:  51.4700, lon:   -0.4543 },
  { iata: "DEN", icao: "KDEN", name: "Denver International",   city: "Denver",        country: "US", lat:  39.8561, lon: -104.6737 },
  { iata: "ORD", icao: "KORD", name: "Chicago O'Hare",         city: "Chicago",       country: "US", lat:  41.9742, lon:  -87.9073 },
  { iata: "IST", icao: "LTFM", name: "Istanbul Airport",       city: "Istanbul",      country: "TR", lat:  41.2750, lon:   28.7519 },
  { iata: "DEL", icao: "VIDP", name: "Indira Gandhi (Delhi)",  city: "Delhi",         country: "IN", lat:  28.5562, lon:   77.1000 },
  { iata: "JFK", icao: "KJFK", name: "John F. Kennedy",        city: "New York",      country: "US", lat:  40.6413, lon:  -73.7781 },
  { iata: "LAX", icao: "KLAX", name: "Los Angeles International", city: "Los Angeles", country: "US", lat:  33.9425, lon: -118.4081 },
  { iata: "CDG", icao: "LFPG", name: "Charles de Gaulle",      city: "Paris",         country: "FR", lat:  49.0097, lon:    2.5479 },
  { iata: "AMS", icao: "EHAM", name: "Schiphol",               city: "Amsterdam",     country: "NL", lat:  52.3105, lon:    4.7683 },
  { iata: "MAD", icao: "LEMD", name: "Madrid Barajas",         city: "Madrid",        country: "ES", lat:  40.4983, lon:   -3.5676 },
  { iata: "FRA", icao: "EDDF", name: "Frankfurt am Main",      city: "Frankfurt",     country: "DE", lat:  50.0379, lon:    8.5622 },
  { iata: "PEK", icao: "ZBAA", name: "Beijing Capital",        city: "Beijing",       country: "CN", lat:  40.0801, lon:  116.5846 },
  { iata: "PVG", icao: "ZSPD", name: "Shanghai Pudong",        city: "Shanghai",      country: "CN", lat:  31.1443, lon:  121.8083 },
  { iata: "CAN", icao: "ZGGG", name: "Guangzhou Baiyun",       city: "Guangzhou",     country: "CN", lat:  23.3924, lon:  113.2988 },
  { iata: "HKG", icao: "VHHH", name: "Hong Kong International", city: "Hong Kong",    country: "HK", lat:  22.3080, lon:  113.9185 },
  { iata: "SIN", icao: "WSSS", name: "Changi",                 city: "Singapore",     country: "SG", lat:   1.3644, lon:  103.9915 },
  { iata: "ICN", icao: "RKSI", name: "Incheon International",  city: "Seoul",         country: "KR", lat:  37.4602, lon:  126.4407 },
  { iata: "BKK", icao: "VTBS", name: "Suvarnabhumi",           city: "Bangkok",       country: "TH", lat:  13.6900, lon:  100.7501 },
  { iata: "KUL", icao: "WMKK", name: "Kuala Lumpur",           city: "Kuala Lumpur",  country: "MY", lat:   2.7456, lon:  101.7099 },
  { iata: "SYD", icao: "YSSY", name: "Sydney Kingsford Smith", city: "Sydney",        country: "AU", lat: -33.9399, lon:  151.1753 },
  { iata: "MEL", icao: "YMML", name: "Melbourne Tullamarine",  city: "Melbourne",     country: "AU", lat: -37.6690, lon:  144.8410 },
  { iata: "GRU", icao: "SBGR", name: "São Paulo–Guarulhos",    city: "São Paulo",     country: "BR", lat: -23.4356, lon:  -46.4731 },
  { iata: "MEX", icao: "MMMX", name: "Benito Juárez (CDMX)",   city: "Mexico City",   country: "MX", lat:  19.4361, lon:  -99.0719 },
  { iata: "YYZ", icao: "CYYZ", name: "Toronto Pearson",        city: "Toronto",       country: "CA", lat:  43.6777, lon:  -79.6248 },
  { iata: "YVR", icao: "CYVR", name: "Vancouver International", city: "Vancouver",    country: "CA", lat:  49.1939, lon: -123.1844 },
  { iata: "BOS", icao: "KBOS", name: "Boston Logan",           city: "Boston",        country: "US", lat:  42.3656, lon:  -71.0096 },
  { iata: "MIA", icao: "KMIA", name: "Miami International",    city: "Miami",         country: "US", lat:  25.7959, lon:  -80.2870 },
  { iata: "SFO", icao: "KSFO", name: "San Francisco",          city: "San Francisco", country: "US", lat:  37.6213, lon: -122.3790 },
  { iata: "SEA", icao: "KSEA", name: "Seattle-Tacoma",         city: "Seattle",       country: "US", lat:  47.4502, lon: -122.3088 },
  { iata: "PHX", icao: "KPHX", name: "Phoenix Sky Harbor",     city: "Phoenix",       country: "US", lat:  33.4373, lon: -112.0078 },
  { iata: "LAS", icao: "KLAS", name: "Harry Reid (Vegas)",     city: "Las Vegas",     country: "US", lat:  36.0840, lon: -115.1537 },
  { iata: "MCO", icao: "KMCO", name: "Orlando International",  city: "Orlando",       country: "US", lat:  28.4312, lon:  -81.3081 },
  { iata: "EWR", icao: "KEWR", name: "Newark Liberty",         city: "Newark",        country: "US", lat:  40.6895, lon:  -74.1745 },
  { iata: "MUC", icao: "EDDM", name: "Munich",                 city: "Munich",        country: "DE", lat:  48.3538, lon:   11.7861 },
  { iata: "FCO", icao: "LIRF", name: "Rome Fiumicino",         city: "Rome",          country: "IT", lat:  41.8003, lon:   12.2389 },
  { iata: "BCN", icao: "LEBL", name: "Barcelona-El Prat",      city: "Barcelona",     country: "ES", lat:  41.2974, lon:    2.0833 },
  { iata: "VIE", icao: "LOWW", name: "Vienna International",   city: "Vienna",        country: "AT", lat:  48.1103, lon:   16.5697 },
  { iata: "ZRH", icao: "LSZH", name: "Zurich",                 city: "Zurich",        country: "CH", lat:  47.4581, lon:    8.5555 },
  { iata: "CPH", icao: "EKCH", name: "Copenhagen Kastrup",     city: "Copenhagen",    country: "DK", lat:  55.6180, lon:   12.6560 },
  { iata: "ARN", icao: "ESSA", name: "Stockholm Arlanda",      city: "Stockholm",     country: "SE", lat:  59.6498, lon:   17.9238 },
  { iata: "OSL", icao: "ENGM", name: "Oslo Gardermoen",        city: "Oslo",          country: "NO", lat:  60.1939, lon:   11.1004 },
  { iata: "HEL", icao: "EFHK", name: "Helsinki Vantaa",        city: "Helsinki",      country: "FI", lat:  60.3172, lon:   24.9633 },
  { iata: "DOH", icao: "OTHH", name: "Hamad International",    city: "Doha",          country: "QA", lat:  25.2731, lon:   51.6080 },
  { iata: "AUH", icao: "OMAA", name: "Abu Dhabi International", city: "Abu Dhabi",    country: "AE", lat:  24.4330, lon:   54.6511 },
  { iata: "JNB", icao: "FAOR", name: "OR Tambo (Joburg)",      city: "Johannesburg",  country: "ZA", lat: -26.1392, lon:   28.2460 },
  { iata: "CPT", icao: "FACT", name: "Cape Town International", city: "Cape Town",    country: "ZA", lat: -33.9648, lon:   18.6017 },
  { iata: "CAI", icao: "HECA", name: "Cairo International",    city: "Cairo",         country: "EG", lat:  30.1219, lon:   31.4056 },
  { iata: "TLV", icao: "LLBG", name: "Ben Gurion",             city: "Tel Aviv",      country: "IL", lat:  32.0114, lon:   34.8867 },
  { iata: "SVO", icao: "UUEE", name: "Sheremetyevo",           city: "Moscow",        country: "RU", lat:  55.9728, lon:   37.4147 },
  { iata: "DME", icao: "UUDD", name: "Domodedovo",             city: "Moscow",        country: "RU", lat:  55.4146, lon:   37.8995 },
  { iata: "WAW", icao: "EPWA", name: "Warsaw Chopin",          city: "Warsaw",        country: "PL", lat:  52.1657, lon:   20.9671 },
  { iata: "BOM", icao: "VABB", name: "Chhatrapati Shivaji",    city: "Mumbai",        country: "IN", lat:  19.0896, lon:   72.8656 },
  { iata: "BLR", icao: "VOBL", name: "Kempegowda (Bangalore)", city: "Bangalore",     country: "IN", lat:  13.1986, lon:   77.7066 },
  { iata: "MAA", icao: "VOMM", name: "Chennai International",  city: "Chennai",       country: "IN", lat:  12.9941, lon:   80.1709 },
  { iata: "KIX", icao: "RJBB", name: "Kansai International",   city: "Osaka",         country: "JP", lat:  34.4347, lon:  135.2330 },
  { iata: "NRT", icao: "RJAA", name: "Narita International",   city: "Tokyo",         country: "JP", lat:  35.7720, lon:  140.3929 },
  { iata: "TPE", icao: "RCTP", name: "Taoyuan International",  city: "Taipei",        country: "TW", lat:  25.0777, lon:  121.2328 },
  { iata: "MNL", icao: "RPLL", name: "Ninoy Aquino",           city: "Manila",        country: "PH", lat:  14.5086, lon:  121.0194 },
  { iata: "CGK", icao: "WIII", name: "Soekarno-Hatta",         city: "Jakarta",       country: "ID", lat:  -6.1256, lon:  106.6559 },
  { iata: "AKL", icao: "NZAA", name: "Auckland International", city: "Auckland",      country: "NZ", lat: -37.0082, lon:  174.7917 },
  { iata: "EZE", icao: "SAEZ", name: "Ministro Pistarini",     city: "Buenos Aires",  country: "AR", lat: -34.8222, lon:  -58.5358 },
  { iata: "SCL", icao: "SCEL", name: "Arturo Merino Benítez",  city: "Santiago",      country: "CL", lat: -33.3928, lon:  -70.7858 },
  { iata: "BOG", icao: "SKBO", name: "El Dorado (Bogotá)",     city: "Bogotá",        country: "CO", lat:   4.7016, lon:  -74.1469 },
  { iata: "LIM", icao: "SPJC", name: "Jorge Chávez (Lima)",    city: "Lima",          country: "PE", lat: -12.0219, lon:  -77.1144 },
  { iata: "SEZ", icao: "FSIA", name: "Seychelles International", city: "Mahé",        country: "SC", lat:  -4.6743, lon:   55.5218 },
  { iata: "REK", icao: "BIKF", name: "Keflavík International", city: "Reykjavík",     country: "IS", lat:  63.9850, lon:  -22.6056 },
  { iata: "DUB", icao: "EIDW", name: "Dublin",                 city: "Dublin",        country: "IE", lat:  53.4213, lon:   -6.2700 },
  { iata: "BRU", icao: "EBBR", name: "Brussels",               city: "Brussels",      country: "BE", lat:  50.9014, lon:    4.4844 },
  { iata: "LIS", icao: "LPPT", name: "Humberto Delgado",       city: "Lisbon",        country: "PT", lat:  38.7813, lon:   -9.1359 },
  { iata: "ATH", icao: "LGAV", name: "Athens Eleftherios Venizelos", city: "Athens",  country: "GR", lat:  37.9364, lon:   23.9445 },
  { iata: "PRG", icao: "LKPR", name: "Václav Havel (Prague)",  city: "Prague",        country: "CZ", lat:  50.1008, lon:   14.2632 },
  { iata: "LGW", icao: "EGKK", name: "London Gatwick",         city: "London",        country: "GB", lat:  51.1481, lon:   -0.1903 },
  { iata: "STN", icao: "EGSS", name: "London Stansted",        city: "London",        country: "GB", lat:  51.8849, lon:    0.2350 },
  { iata: "MAN", icao: "EGCC", name: "Manchester",             city: "Manchester",    country: "GB", lat:  53.3537, lon:   -2.2750 },
  { iata: "LGA", icao: "KLGA", name: "LaGuardia",              city: "New York",      country: "US", lat:  40.7769, lon:  -73.8740 },
  { iata: "DCA", icao: "KDCA", name: "Reagan National",        city: "Washington",    country: "US", lat:  38.8512, lon:  -77.0402 },
  { iata: "IAD", icao: "KIAD", name: "Dulles International",   city: "Washington",    country: "US", lat:  38.9531, lon:  -77.4565 },
  { iata: "HNL", icao: "PHNL", name: "Daniel K. Inouye",       city: "Honolulu",      country: "US", lat:  21.3245, lon: -157.9251 },
  { iata: "ANC", icao: "PANC", name: "Ted Stevens (Anchorage)", city: "Anchorage",    country: "US", lat:  61.1744, lon: -149.9961 },
];
